package com.yashwant.gahlot.Wallet.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)//Here primary key values will be automatically generated by the underlying database system.
    private long uid;

    @NotNull
    @Size(min = 2, message = "First Name should have atelast 2 characters")
    @Column(name = "first_name")
    private String firstName;

    @NotNull
    @Column(name = "mobile")
    private Long mobile;

    @NotNull
    @Size(min = 2, message = "Last Name should have atelast 2 characters")
    @Column(name = "last_name")
    private String lastName;

    @NotBlank
    @Email
    @Column(name = "email")
    private String email;

    @Column(name = "address1")
    private String address1;

    @Column(name = "address2")
    private String address2;


    @Column(name = "haswallet")
    private boolean haswallet;

    @Column(name = "balance")
    private long balance;

    @Column(name = "gender")
    private String gender;

    public User(String firstName, String lastName, String email, String address1, String address2,long mobile) {
        super();
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.address1 = address1;
        this.address2 = address2;
        this.mobile=mobile;
    }
}

/*
* 1. Entity (User): An entity that can be persisted in a database table.  It contains fields representing the columns in the table, along with annotations and constraints to define the mapping and validation rules.
* 2. The class has several fields that represent the columns in the "users" table.
* 3. @Id annotation: This annotation is used to specify the primary key of the entity.
* 4. @Table(name="users"): This annotation is used to specify the name of the database table that corresponds to the entity.
* 5. @GeneratedValue annotation: This annotation is used to specify the strategy for generating the values of the primary key.

 *
* */